[package]
name = "vehicle_speed_publisher"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vehicle-signals = "0.4"
cyclonedds-rs = "0.6.0"
rand = "0.8.4"
